---
- name: Drain Auto Scaling Group (ASG)
  hosts: localhost
  gather_facts: no

  vars:
    aws_region: "ap-southeast-2"

  tasks:
    - name: Drain ASG by setting capacity
      amazon.aws.autoscaling_group:
        name: "{{ asg_name }}"
        min_size: "{{ min_capacity | int }}"
        desired_capacity: "{{ desired_capacity | int }}"
        max_size: "{{ max_capacity | int }}"
        region: "{{ aws_region }}"
